/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PwaImport } from './routes/pwa'
import { Route as PickupPwaImport } from './routes/pickup-pwa'
import { Route as LandingImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebsiteContentIndexImport } from './routes/_authenticated/website-content/index'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTermsAndPoliciesIndexImport } from './routes/_authenticated/terms-and-policies/index'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedShipmentIndexImport } from './routes/_authenticated/shipment/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRatecalcIndexImport } from './routes/_authenticated/ratecalc/index'
import { Route as AuthenticatedPickupsIndexImport } from './routes/_authenticated/pickups/index'
import { Route as AuthenticatedMawbIndexImport } from './routes/_authenticated/mawb/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedForwardingcompanyIndexImport } from './routes/_authenticated/forwardingcompany/index'
import { Route as AuthenticatedCustomersIndexImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomManifestIndexImport } from './routes/_authenticated/custom-manifest/index'
import { Route as AuthenticatedCountryIndexImport } from './routes/_authenticated/country/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAgentsIndexImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'

// Create/Update Routes

const PwaRoute = PwaImport.update({
  id: '/pwa',
  path: '/pwa',
  getParentRoute: () => rootRoute,
} as any)

const PickupPwaRoute = PickupPwaImport.update({
  id: '/pickup-pwa',
  path: '/pickup-pwa',
  getParentRoute: () => rootRoute,
} as any)

const LandingRoute = LandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedWebsiteContentIndexRoute =
  AuthenticatedWebsiteContentIndexImport.update({
    id: '/website-content/',
    path: '/website-content/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTermsAndPoliciesIndexRoute =
  AuthenticatedTermsAndPoliciesIndexImport.update({
    id: '/terms-and-policies/',
    path: '/terms-and-policies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedShipmentIndexRoute = AuthenticatedShipmentIndexImport.update(
  {
    id: '/shipment/',
    path: '/shipment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedRatecalcIndexRoute = AuthenticatedRatecalcIndexImport.update(
  {
    id: '/ratecalc/',
    path: '/ratecalc/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedPickupsIndexRoute = AuthenticatedPickupsIndexImport.update({
  id: '/pickups/',
  path: '/pickups/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedMawbIndexRoute = AuthenticatedMawbIndexImport.update({
  id: '/mawb/',
  path: '/mawb/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedForwardingcompanyIndexRoute =
  AuthenticatedForwardingcompanyIndexImport.update({
    id: '/forwardingcompany/',
    path: '/forwardingcompany/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCustomManifestIndexRoute =
  AuthenticatedCustomManifestIndexImport.update({
    id: '/custom-manifest/',
    path: '/custom-manifest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCountryIndexRoute = AuthenticatedCountryIndexImport.update({
  id: '/country/',
  path: '/country/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAgentsIndexRoute = AuthenticatedAgentsIndexImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/pickup-pwa': {
      id: '/pickup-pwa'
      path: '/pickup-pwa'
      fullPath: '/pickup-pwa'
      preLoaderRoute: typeof PickupPwaImport
      parentRoute: typeof rootRoute
    }
    '/pwa': {
      id: '/pwa'
      path: '/pwa'
      fullPath: '/pwa'
      preLoaderRoute: typeof PwaImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/country/': {
      id: '/_authenticated/country/'
      path: '/country'
      fullPath: '/country'
      preLoaderRoute: typeof AuthenticatedCountryIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/custom-manifest/': {
      id: '/_authenticated/custom-manifest/'
      path: '/custom-manifest'
      fullPath: '/custom-manifest'
      preLoaderRoute: typeof AuthenticatedCustomManifestIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/forwardingcompany/': {
      id: '/_authenticated/forwardingcompany/'
      path: '/forwardingcompany'
      fullPath: '/forwardingcompany'
      preLoaderRoute: typeof AuthenticatedForwardingcompanyIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/mawb/': {
      id: '/_authenticated/mawb/'
      path: '/mawb'
      fullPath: '/mawb'
      preLoaderRoute: typeof AuthenticatedMawbIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/pickups/': {
      id: '/_authenticated/pickups/'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof AuthenticatedPickupsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/ratecalc/': {
      id: '/_authenticated/ratecalc/'
      path: '/ratecalc'
      fullPath: '/ratecalc'
      preLoaderRoute: typeof AuthenticatedRatecalcIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/shipment/': {
      id: '/_authenticated/shipment/'
      path: '/shipment'
      fullPath: '/shipment'
      preLoaderRoute: typeof AuthenticatedShipmentIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/terms-and-policies/': {
      id: '/_authenticated/terms-and-policies/'
      path: '/terms-and-policies'
      fullPath: '/terms-and-policies'
      preLoaderRoute: typeof AuthenticatedTermsAndPoliciesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/website-content/': {
      id: '/_authenticated/website-content/'
      path: '/website-content'
      fullPath: '/website-content'
      preLoaderRoute: typeof AuthenticatedWebsiteContentIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCountryIndexRoute: typeof AuthenticatedCountryIndexRoute
  AuthenticatedCustomManifestIndexRoute: typeof AuthenticatedCustomManifestIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedForwardingcompanyIndexRoute: typeof AuthenticatedForwardingcompanyIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMawbIndexRoute: typeof AuthenticatedMawbIndexRoute
  AuthenticatedPickupsIndexRoute: typeof AuthenticatedPickupsIndexRoute
  AuthenticatedRatecalcIndexRoute: typeof AuthenticatedRatecalcIndexRoute
  AuthenticatedShipmentIndexRoute: typeof AuthenticatedShipmentIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTermsAndPoliciesIndexRoute: typeof AuthenticatedTermsAndPoliciesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebsiteContentIndexRoute: typeof AuthenticatedWebsiteContentIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCountryIndexRoute: AuthenticatedCountryIndexRoute,
  AuthenticatedCustomManifestIndexRoute: AuthenticatedCustomManifestIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedForwardingcompanyIndexRoute:
    AuthenticatedForwardingcompanyIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMawbIndexRoute: AuthenticatedMawbIndexRoute,
  AuthenticatedPickupsIndexRoute: AuthenticatedPickupsIndexRoute,
  AuthenticatedRatecalcIndexRoute: AuthenticatedRatecalcIndexRoute,
  AuthenticatedShipmentIndexRoute: AuthenticatedShipmentIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTermsAndPoliciesIndexRoute:
    AuthenticatedTermsAndPoliciesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebsiteContentIndexRoute: AuthenticatedWebsiteContentIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/pickup-pwa': typeof PickupPwaRoute
  '/pwa': typeof PwaRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/country': typeof AuthenticatedCountryIndexRoute
  '/custom-manifest': typeof AuthenticatedCustomManifestIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/forwardingcompany': typeof AuthenticatedForwardingcompanyIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/mawb': typeof AuthenticatedMawbIndexRoute
  '/pickups': typeof AuthenticatedPickupsIndexRoute
  '/ratecalc': typeof AuthenticatedRatecalcIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shipment': typeof AuthenticatedShipmentIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/terms-and-policies': typeof AuthenticatedTermsAndPoliciesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/website-content': typeof AuthenticatedWebsiteContentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/pickup-pwa': typeof PickupPwaRoute
  '/pwa': typeof PwaRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/country': typeof AuthenticatedCountryIndexRoute
  '/custom-manifest': typeof AuthenticatedCustomManifestIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/forwardingcompany': typeof AuthenticatedForwardingcompanyIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/mawb': typeof AuthenticatedMawbIndexRoute
  '/pickups': typeof AuthenticatedPickupsIndexRoute
  '/ratecalc': typeof AuthenticatedRatecalcIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shipment': typeof AuthenticatedShipmentIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/terms-and-policies': typeof AuthenticatedTermsAndPoliciesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/website-content': typeof AuthenticatedWebsiteContentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/pickup-pwa': typeof PickupPwaRoute
  '/pwa': typeof PwaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/country/': typeof AuthenticatedCountryIndexRoute
  '/_authenticated/custom-manifest/': typeof AuthenticatedCustomManifestIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/forwardingcompany/': typeof AuthenticatedForwardingcompanyIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/mawb/': typeof AuthenticatedMawbIndexRoute
  '/_authenticated/pickups/': typeof AuthenticatedPickupsIndexRoute
  '/_authenticated/ratecalc/': typeof AuthenticatedRatecalcIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shipment/': typeof AuthenticatedShipmentIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/terms-and-policies/': typeof AuthenticatedTermsAndPoliciesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/website-content/': typeof AuthenticatedWebsiteContentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/landing'
    | '/pickup-pwa'
    | '/pwa'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/agents'
    | '/apps'
    | '/chats'
    | '/country'
    | '/custom-manifest'
    | '/customers'
    | '/forwardingcompany'
    | '/help-center'
    | '/mawb'
    | '/pickups'
    | '/ratecalc'
    | '/settings/'
    | '/shipment'
    | '/tasks'
    | '/terms-and-policies'
    | '/users'
    | '/website-content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/landing'
    | '/pickup-pwa'
    | '/pwa'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/agents'
    | '/apps'
    | '/chats'
    | '/country'
    | '/custom-manifest'
    | '/customers'
    | '/forwardingcompany'
    | '/help-center'
    | '/mawb'
    | '/pickups'
    | '/ratecalc'
    | '/settings'
    | '/shipment'
    | '/tasks'
    | '/terms-and-policies'
    | '/users'
    | '/website-content'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/landing'
    | '/pickup-pwa'
    | '/pwa'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/agents/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/country/'
    | '/_authenticated/custom-manifest/'
    | '/_authenticated/customers/'
    | '/_authenticated/forwardingcompany/'
    | '/_authenticated/help-center/'
    | '/_authenticated/mawb/'
    | '/_authenticated/pickups/'
    | '/_authenticated/ratecalc/'
    | '/_authenticated/settings/'
    | '/_authenticated/shipment/'
    | '/_authenticated/tasks/'
    | '/_authenticated/terms-and-policies/'
    | '/_authenticated/users/'
    | '/_authenticated/website-content/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
  PickupPwaRoute: typeof PickupPwaRoute
  PwaRoute: typeof PwaRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LandingRoute: LandingRoute,
  PickupPwaRoute: PickupPwaRoute,
  PwaRoute: PwaRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/landing",
        "/pickup-pwa",
        "/pwa",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/dashboard",
        "/_authenticated/agents/",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/country/",
        "/_authenticated/custom-manifest/",
        "/_authenticated/customers/",
        "/_authenticated/forwardingcompany/",
        "/_authenticated/help-center/",
        "/_authenticated/mawb/",
        "/_authenticated/pickups/",
        "/_authenticated/ratecalc/",
        "/_authenticated/shipment/",
        "/_authenticated/tasks/",
        "/_authenticated/terms-and-policies/",
        "/_authenticated/users/",
        "/_authenticated/website-content/"
      ]
    },
    "/landing": {
      "filePath": "landing.tsx"
    },
    "/pickup-pwa": {
      "filePath": "pickup-pwa.tsx"
    },
    "/pwa": {
      "filePath": "pwa.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/agents/": {
      "filePath": "_authenticated/agents/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/country/": {
      "filePath": "_authenticated/country/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/custom-manifest/": {
      "filePath": "_authenticated/custom-manifest/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/": {
      "filePath": "_authenticated/customers/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/forwardingcompany/": {
      "filePath": "_authenticated/forwardingcompany/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/mawb/": {
      "filePath": "_authenticated/mawb/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pickups/": {
      "filePath": "_authenticated/pickups/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ratecalc/": {
      "filePath": "_authenticated/ratecalc/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/shipment/": {
      "filePath": "_authenticated/shipment/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/terms-and-policies/": {
      "filePath": "_authenticated/terms-and-policies/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/website-content/": {
      "filePath": "_authenticated/website-content/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
