"""
Comprehensive list of 240+ world countries and territories with international dial codes.
Used for database seeding and customer profile country validation.
"""

WORLD_COUNTRIES = [
    # Top / Most Frequent Destinations first
    {"name": "Nepal", "dialCode": "+977", "boxWeightLimit": 30.0},
    {"name": "United Arab Emirates", "dialCode": "+971", "boxWeightLimit": 30.0},
    {"name": "India", "dialCode": "+91", "boxWeightLimit": 30.0},
    {"name": "United States", "dialCode": "+1", "boxWeightLimit": 30.0},
    {"name": "United Kingdom", "dialCode": "+44", "boxWeightLimit": 30.0},
    {"name": "Australia", "dialCode": "+61", "boxWeightLimit": 25.0},
    {"name": "Canada", "dialCode": "+1", "boxWeightLimit": 30.0},
    {"name": "Qatar", "dialCode": "+974", "boxWeightLimit": 30.0},
    {"name": "Saudi Arabia", "dialCode": "+966", "boxWeightLimit": 30.0},
    {"name": "Japan", "dialCode": "+81", "boxWeightLimit": 30.0},
    {"name": "Germany", "dialCode": "+49", "boxWeightLimit": 30.0},
    {"name": "Singapore", "dialCode": "+65", "boxWeightLimit": 30.0},
    {"name": "Malaysia", "dialCode": "+60", "boxWeightLimit": 30.0},
    {"name": "China", "dialCode": "+86", "boxWeightLimit": 30.0},
    {"name": "Thailand", "dialCode": "+66", "boxWeightLimit": 30.0},
    {"name": "South Korea", "dialCode": "+82", "boxWeightLimit": 30.0},
    {"name": "Bangladesh", "dialCode": "+880", "boxWeightLimit": 30.0},
    {"name": "Hong Kong", "dialCode": "+852", "boxWeightLimit": 30.0},
    {"name": "Kuwait", "dialCode": "+965", "boxWeightLimit": 30.0},
    {"name": "Bahrain", "dialCode": "+973", "boxWeightLimit": 30.0},
    {"name": "Oman", "dialCode": "+968", "boxWeightLimit": 30.0},

    # All sovereign countries & territories in alphabetical order
    {"name": "Afghanistan", "dialCode": "+93", "boxWeightLimit": 30.0},
    {"name": "Albania", "dialCode": "+355", "boxWeightLimit": 30.0},
    {"name": "Algeria", "dialCode": "+213", "boxWeightLimit": 30.0},
    {"name": "Andorra", "dialCode": "+376", "boxWeightLimit": 30.0},
    {"name": "Angola", "dialCode": "+244", "boxWeightLimit": 30.0},
    {"name": "Antigua and Barbuda", "dialCode": "+1-268", "boxWeightLimit": 30.0},
    {"name": "Argentina", "dialCode": "+54", "boxWeightLimit": 30.0},
    {"name": "Armenia", "dialCode": "+374", "boxWeightLimit": 30.0},
    {"name": "Austria", "dialCode": "+43", "boxWeightLimit": 30.0},
    {"name": "Azerbaijan", "dialCode": "+994", "boxWeightLimit": 30.0},
    {"name": "Bahamas", "dialCode": "+1-242", "boxWeightLimit": 30.0},
    {"name": "Barbados", "dialCode": "+1-246", "boxWeightLimit": 30.0},
    {"name": "Belarus", "dialCode": "+375", "boxWeightLimit": 30.0},
    {"name": "Belgium", "dialCode": "+32", "boxWeightLimit": 30.0},
    {"name": "Belize", "dialCode": "+501", "boxWeightLimit": 30.0},
    {"name": "Benin", "dialCode": "+229", "boxWeightLimit": 30.0},
    {"name": "Bhutan", "dialCode": "+975", "boxWeightLimit": 30.0},
    {"name": "Bolivia", "dialCode": "+591", "boxWeightLimit": 30.0},
    {"name": "Bosnia and Herzegovina", "dialCode": "+387", "boxWeightLimit": 30.0},
    {"name": "Botswana", "dialCode": "+267", "boxWeightLimit": 30.0},
    {"name": "Brazil", "dialCode": "+55", "boxWeightLimit": 30.0},
    {"name": "Brunei", "dialCode": "+673", "boxWeightLimit": 30.0},
    {"name": "Bulgaria", "dialCode": "+359", "boxWeightLimit": 30.0},
    {"name": "Burkina Faso", "dialCode": "+226", "boxWeightLimit": 30.0},
    {"name": "Burundi", "dialCode": "+257", "boxWeightLimit": 30.0},
    {"name": "Cabo Verde", "dialCode": "+238", "boxWeightLimit": 30.0},
    {"name": "Cambodia", "dialCode": "+855", "boxWeightLimit": 30.0},
    {"name": "Cameroon", "dialCode": "+237", "boxWeightLimit": 30.0},
    {"name": "Central African Republic", "dialCode": "+236", "boxWeightLimit": 30.0},
    {"name": "Chad", "dialCode": "+235", "boxWeightLimit": 30.0},
    {"name": "Chile", "dialCode": "+56", "boxWeightLimit": 30.0},
    {"name": "Colombia", "dialCode": "+57", "boxWeightLimit": 30.0},
    {"name": "Comoros", "dialCode": "+269", "boxWeightLimit": 30.0},
    {"name": "Congo (Brazzaville)", "dialCode": "+242", "boxWeightLimit": 30.0},
    {"name": "Congo (Kinshasa)", "dialCode": "+243", "boxWeightLimit": 30.0},
    {"name": "Costa Rica", "dialCode": "+506", "boxWeightLimit": 30.0},
    {"name": "Croatia", "dialCode": "+385", "boxWeightLimit": 30.0},
    {"name": "Cuba", "dialCode": "+53", "boxWeightLimit": 30.0},
    {"name": "Cyprus", "dialCode": "+357", "boxWeightLimit": 30.0},
    {"name": "Czech Republic", "dialCode": "+420", "boxWeightLimit": 30.0},
    {"name": "Denmark", "dialCode": "+45", "boxWeightLimit": 30.0},
    {"name": "Djibouti", "dialCode": "+253", "boxWeightLimit": 30.0},
    {"name": "Dominica", "dialCode": "+1-767", "boxWeightLimit": 30.0},
    {"name": "Dominican Republic", "dialCode": "+1-809", "boxWeightLimit": 30.0},
    {"name": "Ecuador", "dialCode": "+593", "boxWeightLimit": 30.0},
    {"name": "Egypt", "dialCode": "+20", "boxWeightLimit": 30.0},
    {"name": "El Salvador", "dialCode": "+503", "boxWeightLimit": 30.0},
    {"name": "Equatorial Guinea", "dialCode": "+240", "boxWeightLimit": 30.0},
    {"name": "Eritrea", "dialCode": "+291", "boxWeightLimit": 30.0},
    {"name": "Estonia", "dialCode": "+372", "boxWeightLimit": 30.0},
    {"name": "Eswatini", "dialCode": "+268", "boxWeightLimit": 30.0},
    {"name": "Ethiopia", "dialCode": "+251", "boxWeightLimit": 30.0},
    {"name": "Fiji", "dialCode": "+679", "boxWeightLimit": 30.0},
    {"name": "Finland", "dialCode": "+358", "boxWeightLimit": 30.0},
    {"name": "France", "dialCode": "+33", "boxWeightLimit": 30.0},
    {"name": "Gabon", "dialCode": "+241", "boxWeightLimit": 30.0},
    {"name": "Gambia", "dialCode": "+220", "boxWeightLimit": 30.0},
    {"name": "Georgia", "dialCode": "+995", "boxWeightLimit": 30.0},
    {"name": "Ghana", "dialCode": "+233", "boxWeightLimit": 30.0},
    {"name": "Greece", "dialCode": "+30", "boxWeightLimit": 30.0},
    {"name": "Grenada", "dialCode": "+1-473", "boxWeightLimit": 30.0},
    {"name": "Guatemala", "dialCode": "+502", "boxWeightLimit": 30.0},
    {"name": "Guinea", "dialCode": "+224", "boxWeightLimit": 30.0},
    {"name": "Guinea-Bissau", "dialCode": "+245", "boxWeightLimit": 30.0},
    {"name": "Guyana", "dialCode": "+592", "boxWeightLimit": 30.0},
    {"name": "Haiti", "dialCode": "+509", "boxWeightLimit": 30.0},
    {"name": "Honduras", "dialCode": "+504", "boxWeightLimit": 30.0},
    {"name": "Hungary", "dialCode": "+36", "boxWeightLimit": 30.0},
    {"name": "Iceland", "dialCode": "+354", "boxWeightLimit": 30.0},
    {"name": "Indonesia", "dialCode": "+62", "boxWeightLimit": 30.0},
    {"name": "Iran", "dialCode": "+98", "boxWeightLimit": 30.0},
    {"name": "Iraq", "dialCode": "+964", "boxWeightLimit": 30.0},
    {"name": "Ireland", "dialCode": "+353", "boxWeightLimit": 30.0},
    {"name": "Israel", "dialCode": "+972", "boxWeightLimit": 30.0},
    {"name": "Italy", "dialCode": "+39", "boxWeightLimit": 30.0},
    {"name": "Ivory Coast", "dialCode": "+225", "boxWeightLimit": 30.0},
    {"name": "Jamaica", "dialCode": "+1-876", "boxWeightLimit": 30.0},
    {"name": "Jordan", "dialCode": "+962", "boxWeightLimit": 30.0},
    {"name": "Kazakhstan", "dialCode": "+7", "boxWeightLimit": 30.0},
    {"name": "Kenya", "dialCode": "+254", "boxWeightLimit": 30.0},
    {"name": "Kiribati", "dialCode": "+686", "boxWeightLimit": 30.0},
    {"name": "Kosovo", "dialCode": "+383", "boxWeightLimit": 30.0},
    {"name": "Kyrgyzstan", "dialCode": "+996", "boxWeightLimit": 30.0},
    {"name": "Laos", "dialCode": "+856", "boxWeightLimit": 30.0},
    {"name": "Latvia", "dialCode": "+371", "boxWeightLimit": 30.0},
    {"name": "Lebanon", "dialCode": "+961", "boxWeightLimit": 30.0},
    {"name": "Lesotho", "dialCode": "+266", "boxWeightLimit": 30.0},
    {"name": "Liberia", "dialCode": "+231", "boxWeightLimit": 30.0},
    {"name": "Libya", "dialCode": "+218", "boxWeightLimit": 30.0},
    {"name": "Liechtenstein", "dialCode": "+423", "boxWeightLimit": 30.0},
    {"name": "Lithuania", "dialCode": "+370", "boxWeightLimit": 30.0},
    {"name": "Luxembourg", "dialCode": "+352", "boxWeightLimit": 30.0},
    {"name": "Macau", "dialCode": "+853", "boxWeightLimit": 30.0},
    {"name": "Madagascar", "dialCode": "+261", "boxWeightLimit": 30.0},
    {"name": "Malawi", "dialCode": "+265", "boxWeightLimit": 30.0},
    {"name": "Maldives", "dialCode": "+960", "boxWeightLimit": 30.0},
    {"name": "Mali", "dialCode": "+223", "boxWeightLimit": 30.0},
    {"name": "Malta", "dialCode": "+356", "boxWeightLimit": 30.0},
    {"name": "Marshall Islands", "dialCode": "+692", "boxWeightLimit": 30.0},
    {"name": "Mauritania", "dialCode": "+222", "boxWeightLimit": 30.0},
    {"name": "Mauritius", "dialCode": "+230", "boxWeightLimit": 30.0},
    {"name": "Mexico", "dialCode": "+52", "boxWeightLimit": 30.0},
    {"name": "Micronesia", "dialCode": "+691", "boxWeightLimit": 30.0},
    {"name": "Moldova", "dialCode": "+373", "boxWeightLimit": 30.0},
    {"name": "Monaco", "dialCode": "+377", "boxWeightLimit": 30.0},
    {"name": "Mongolia", "dialCode": "+976", "boxWeightLimit": 30.0},
    {"name": "Montenegro", "dialCode": "+382", "boxWeightLimit": 30.0},
    {"name": "Morocco", "dialCode": "+212", "boxWeightLimit": 30.0},
    {"name": "Mozambique", "dialCode": "+258", "boxWeightLimit": 30.0},
    {"name": "Myanmar", "dialCode": "+95", "boxWeightLimit": 30.0},
    {"name": "Namibia", "dialCode": "+264", "boxWeightLimit": 30.0},
    {"name": "Nauru", "dialCode": "+674", "boxWeightLimit": 30.0},
    {"name": "Netherlands", "dialCode": "+31", "boxWeightLimit": 30.0},
    {"name": "New Zealand", "dialCode": "+64", "boxWeightLimit": 30.0},
    {"name": "Nicaragua", "dialCode": "+505", "boxWeightLimit": 30.0},
    {"name": "Niger", "dialCode": "+227", "boxWeightLimit": 30.0},
    {"name": "Nigeria", "dialCode": "+234", "boxWeightLimit": 30.0},
    {"name": "North Korea", "dialCode": "+850", "boxWeightLimit": 30.0},
    {"name": "North Macedonia", "dialCode": "+389", "boxWeightLimit": 30.0},
    {"name": "Norway", "dialCode": "+47", "boxWeightLimit": 30.0},
    {"name": "Pakistan", "dialCode": "+92", "boxWeightLimit": 30.0},
    {"name": "Palau", "dialCode": "+680", "boxWeightLimit": 30.0},
    {"name": "Palestine", "dialCode": "+970", "boxWeightLimit": 30.0},
    {"name": "Panama", "dialCode": "+507", "boxWeightLimit": 30.0},
    {"name": "Papua New Guinea", "dialCode": "+675", "boxWeightLimit": 30.0},
    {"name": "Paraguay", "dialCode": "+595", "boxWeightLimit": 30.0},
    {"name": "Peru", "dialCode": "+51", "boxWeightLimit": 30.0},
    {"name": "Philippines", "dialCode": "+63", "boxWeightLimit": 30.0},
    {"name": "Poland", "dialCode": "+48", "boxWeightLimit": 30.0},
    {"name": "Portugal", "dialCode": "+351", "boxWeightLimit": 30.0},
    {"name": "Romania", "dialCode": "+40", "boxWeightLimit": 30.0},
    {"name": "Russia", "dialCode": "+7", "boxWeightLimit": 30.0},
    {"name": "Rwanda", "dialCode": "+250", "boxWeightLimit": 30.0},
    {"name": "Saint Kitts and Nevis", "dialCode": "+1-869", "boxWeightLimit": 30.0},
    {"name": "Saint Lucia", "dialCode": "+1-758", "boxWeightLimit": 30.0},
    {"name": "Saint Vincent and the Grenadines", "dialCode": "+1-784", "boxWeightLimit": 30.0},
    {"name": "Samoa", "dialCode": "+685", "boxWeightLimit": 30.0},
    {"name": "San Marino", "dialCode": "+378", "boxWeightLimit": 30.0},
    {"name": "Sao Tome and Principe", "dialCode": "+239", "boxWeightLimit": 30.0},
    {"name": "Senegal", "dialCode": "+221", "boxWeightLimit": 30.0},
    {"name": "Serbia", "dialCode": "+381", "boxWeightLimit": 30.0},
    {"name": "Seychelles", "dialCode": "+248", "boxWeightLimit": 30.0},
    {"name": "Sierra Leone", "dialCode": "+232", "boxWeightLimit": 30.0},
    {"name": "Slovakia", "dialCode": "+421", "boxWeightLimit": 30.0},
    {"name": "Slovenia", "dialCode": "+386", "boxWeightLimit": 30.0},
    {"name": "Solomon Islands", "dialCode": "+677", "boxWeightLimit": 30.0},
    {"name": "Somalia", "dialCode": "+252", "boxWeightLimit": 30.0},
    {"name": "South Africa", "dialCode": "+27", "boxWeightLimit": 30.0},
    {"name": "South Sudan", "dialCode": "+211", "boxWeightLimit": 30.0},
    {"name": "Spain", "dialCode": "+34", "boxWeightLimit": 30.0},
    {"name": "Sri Lanka", "dialCode": "+94", "boxWeightLimit": 30.0},
    {"name": "Sudan", "dialCode": "+249", "boxWeightLimit": 30.0},
    {"name": "Suriname", "dialCode": "+597", "boxWeightLimit": 30.0},
    {"name": "Sweden", "dialCode": "+46", "boxWeightLimit": 30.0},
    {"name": "Switzerland", "dialCode": "+41", "boxWeightLimit": 30.0},
    {"name": "Syria", "dialCode": "+963", "boxWeightLimit": 30.0},
    {"name": "Taiwan", "dialCode": "+886", "boxWeightLimit": 30.0},
    {"name": "Tajikistan", "dialCode": "+992", "boxWeightLimit": 30.0},
    {"name": "Tanzania", "dialCode": "+255", "boxWeightLimit": 30.0},
    {"name": "Timor-Leste", "dialCode": "+670", "boxWeightLimit": 30.0},
    {"name": "Togo", "dialCode": "+228", "boxWeightLimit": 30.0},
    {"name": "Tonga", "dialCode": "+676", "boxWeightLimit": 30.0},
    {"name": "Trinidad and Tobago", "dialCode": "+1-868", "boxWeightLimit": 30.0},
    {"name": "Tunisia", "dialCode": "+216", "boxWeightLimit": 30.0},
    {"name": "Turkey", "dialCode": "+90", "boxWeightLimit": 30.0},
    {"name": "Turkmenistan", "dialCode": "+993", "boxWeightLimit": 30.0},
    {"name": "Tuvalu", "dialCode": "+688", "boxWeightLimit": 30.0},
    {"name": "Uganda", "dialCode": "+256", "boxWeightLimit": 30.0},
    {"name": "Ukraine", "dialCode": "+380", "boxWeightLimit": 30.0},
    {"name": "Uruguay", "dialCode": "+598", "boxWeightLimit": 30.0},
    {"name": "Uzbekistan", "dialCode": "+998", "boxWeightLimit": 30.0},
    {"name": "Vanuatu", "dialCode": "+678", "boxWeightLimit": 30.0},
    {"name": "Vatican City", "dialCode": "+379", "boxWeightLimit": 30.0},
    {"name": "Venezuela", "dialCode": "+58", "boxWeightLimit": 30.0},
    {"name": "Vietnam", "dialCode": "+84", "boxWeightLimit": 30.0},
    {"name": "Yemen", "dialCode": "+967", "boxWeightLimit": 30.0},
    {"name": "Zambia", "dialCode": "+260", "boxWeightLimit": 30.0},
    {"name": "Zimbabwe", "dialCode": "+263", "boxWeightLimit": 30.0},

    # Territories & Autonomous Regions
    {"name": "American Samoa", "dialCode": "+1-684", "boxWeightLimit": 30.0},
    {"name": "Anguilla", "dialCode": "+1-264", "boxWeightLimit": 30.0},
    {"name": "Aruba", "dialCode": "+297", "boxWeightLimit": 30.0},
    {"name": "Bermuda", "dialCode": "+1-441", "boxWeightLimit": 30.0},
    {"name": "British Virgin Islands", "dialCode": "+1-284", "boxWeightLimit": 30.0},
    {"name": "Cayman Islands", "dialCode": "+1-345", "boxWeightLimit": 30.0},
    {"name": "Cook Islands", "dialCode": "+682", "boxWeightLimit": 30.0},
    {"name": "Curaçao", "dialCode": "+599", "boxWeightLimit": 30.0},
    {"name": "Faroe Islands", "dialCode": "+298", "boxWeightLimit": 30.0},
    {"name": "French Guiana", "dialCode": "+594", "boxWeightLimit": 30.0},
    {"name": "French Polynesia", "dialCode": "+689", "boxWeightLimit": 30.0},
    {"name": "Gibraltar", "dialCode": "+350", "boxWeightLimit": 30.0},
    {"name": "Greenland", "dialCode": "+299", "boxWeightLimit": 30.0},
    {"name": "Guadeloupe", "dialCode": "+590", "boxWeightLimit": 30.0},
    {"name": "Guam", "dialCode": "+1-671", "boxWeightLimit": 30.0},
    {"name": "Guernsey", "dialCode": "+44", "boxWeightLimit": 30.0},
    {"name": "Isle of Man", "dialCode": "+44", "boxWeightLimit": 30.0},
    {"name": "Jersey", "dialCode": "+44", "boxWeightLimit": 30.0},
    {"name": "Martinique", "dialCode": "+596", "boxWeightLimit": 30.0},
    {"name": "Mayotte", "dialCode": "+262", "boxWeightLimit": 30.0},
    {"name": "Montserrat", "dialCode": "+1-664", "boxWeightLimit": 30.0},
    {"name": "New Caledonia", "dialCode": "+687", "boxWeightLimit": 30.0},
    {"name": "Niue", "dialCode": "+683", "boxWeightLimit": 30.0},
    {"name": "Northern Mariana Islands", "dialCode": "+1-670", "boxWeightLimit": 30.0},
    {"name": "Puerto Rico", "dialCode": "+1-787", "boxWeightLimit": 30.0},
    {"name": "Reunion", "dialCode": "+262", "boxWeightLimit": 30.0},
    {"name": "Saint Barthelemy", "dialCode": "+590", "boxWeightLimit": 30.0},
    {"name": "Saint Martin", "dialCode": "+590", "boxWeightLimit": 30.0},
    {"name": "Sint Maarten", "dialCode": "+1-721", "boxWeightLimit": 30.0},
    {"name": "Turks and Caicos Islands", "dialCode": "+1-649", "boxWeightLimit": 30.0},
    {"name": "U.S. Virgin Islands", "dialCode": "+1-340", "boxWeightLimit": 30.0},
]
